// Dictionnaire des noms d'équipes
// Nom courant → Nom officiel API-Football

const TEAM_NAMES = {
  // ==================== PREMIER LEAGUE ====================
  'arsenal': 'Arsenal',
  'liverpool': 'Liverpool',
  'man city': 'Manchester City',
  'manchester city': 'Manchester City',
  'city': 'Manchester City',
  'man utd': 'Manchester United',
  'man united': 'Manchester United',
  'manchester united': 'Manchester United',
  'united': 'Manchester United',
  'chelsea': 'Chelsea',
  'tottenham': 'Tottenham',
  'spurs': 'Tottenham',
  'newcastle': 'Newcastle',
  'newcastle united': 'Newcastle',
  'brighton': 'Brighton',
  'aston villa': 'Aston Villa',
  'villa': 'Aston Villa',
  'west ham': 'West Ham',
  'crystal palace': 'Crystal Palace',
  'palace': 'Crystal Palace',
  'wolves': 'Wolves',
  'wolverhampton': 'Wolves',
  'fulham': 'Fulham',
  'brentford': 'Brentford',
  'nottingham': 'Nottingham Forest',
  'forest': 'Nottingham Forest',
  'everton': 'Everton',
  'bournemouth': 'Bournemouth',
  'leicester': 'Leicester',
  'leeds': 'Leeds',
  'southampton': 'Southampton',
  
  // ==================== LIGUE 1 ====================
  'psg': 'Paris Saint Germain',
  'paris': 'Paris Saint Germain',
  'paris sg': 'Paris Saint Germain',
  'om': 'Marseille',
  'marseille': 'Marseille',
  'lyon': 'Lyon',
  'ol': 'Lyon',
  'olympique lyonnais': 'Lyon',
  'lille': 'Lille',
  'monaco': 'Monaco',
  'as monaco': 'Monaco',
  'nice': 'Nice',
  'lens': 'Lens',
  'rc lens': 'Lens',
  'rennes': 'Rennes',
  'nantes': 'Nantes',
  'strasbourg': 'Strasbourg',
  'reims': 'Reims',
  'toulouse': 'Toulouse',
  'montpellier': 'Montpellier',
  'brest': 'Brest',
  'angers': 'Angers',
  'le havre': 'Le Havre',
  'lorient': 'Lorient',
  'clermont': 'Clermont Foot',
  'metz': 'Metz',
  
  // ==================== LA LIGA ====================
  'real': 'Real Madrid',
  'real madrid': 'Real Madrid',
  'madrid': 'Real Madrid',
  'barca': 'Barcelona',
  'barcelone': 'Barcelona',
  'barcelona': 'Barcelona',
  'barça': 'Barcelona',
  'atletico': 'Atletico Madrid',
  'atleti': 'Atletico Madrid',
  'atletico madrid': 'Atletico Madrid',
  'sevilla': 'Sevilla',
  'seville': 'Sevilla',
  'real sociedad': 'Real Sociedad',
  'sociedad': 'Real Sociedad',
  'betis': 'Real Betis',
  'real betis': 'Real Betis',
  'villarreal': 'Villarreal',
  'valencia': 'Valencia',
  'valence': 'Valencia',
  'athletic': 'Athletic Club',
  'bilbao': 'Athletic Club',
  'athletic bilbao': 'Athletic Club',
  'getafe': 'Getafe',
  'girona': 'Girona',
  'osasuna': 'Osasuna',
  'rayo': 'Rayo Vallecano',
  'rayo vallecano': 'Rayo Vallecano',
  'celta': 'Celta Vigo',
  'celta vigo': 'Celta Vigo',
  'mallorca': 'Mallorca',
  'las palmas': 'Las Palmas',
  'alaves': 'Deportivo Alaves',
  'deportivo alaves': 'Deportivo Alaves',
  
  // ==================== BUNDESLIGA ====================
  'bayern': 'Bayern München',
  'bayern munich': 'Bayern München',
  'dortmund': 'Borussia Dortmund',
  'bvb': 'Borussia Dortmund',
  'borussia dortmund': 'Borussia Dortmund',
  'leipzig': 'RB Leipzig',
  'rb leipzig': 'RB Leipzig',
  'leverkusen': 'Bayer Leverkusen',
  'bayer': 'Bayer Leverkusen',
  'bayer leverkusen': 'Bayer Leverkusen',
  'union berlin': 'Union Berlin',
  'berlin': 'Union Berlin',
  'freiburg': 'SC Freiburg',
  'frankfurt': 'Eintracht Frankfurt',
  'eintracht': 'Eintracht Frankfurt',
  'wolfsburg': 'VfL Wolfsburg',
  'monchengladbach': 'Borussia Mönchengladbach',
  'gladbach': 'Borussia Mönchengladbach',
  'mainz': 'FSV Mainz 05',
  'hoffenheim': '1899 Hoffenheim',
  'cologne': '1. FC Köln',
  'koln': '1. FC Köln',
  'werder': 'Werder Bremen',
  'bremen': 'Werder Bremen',
  'bochum': 'VfL Bochum',
  'augsburg': 'FC Augsburg',
  'stuttgart': 'VfB Stuttgart',
  'st pauli' : 'FC St. Pauli',
  'heidenheim' : '1. FC Heidenheim',
  'hambourg' : 'Hamburger SV',
  
  // ==================== SERIE A ====================
  'juve': 'Juventus',
  'juventus': 'Juventus',
  'inter': 'Inter',
  'inter milan': 'Inter',
  'milan': 'AC Milan',
  'ac milan': 'AC Milan',
  'napoli': 'Napoli',
  'naples': 'Napoli',
  'roma': 'AS Roma',
  'rome': 'AS Roma',
  'as roma': 'AS Roma',
  'lazio': 'Lazio',
  'atalanta': 'Atalanta',
  'fiorentina': 'Fiorentina',
  'florence': 'Fiorentina',
  'torino': 'Torino',
  'turin': 'Torino',
  'bologna': 'Bologna',
  'bologne': 'Bologna',
  'udinese': 'Udinese',
  'sassuolo': 'Sassuolo',
  'monza': 'Monza',
  'lecce': 'Lecce',
  'verona': 'Verona',
  'hellas verona': 'Verona',
  'empoli': 'Empoli',
  'salernitana': 'Salernitana',
  'cagliari': 'Cagliari',
  'frosinone': 'Frosinone',
  'genoa': 'Genoa',
  'sampdoria': 'Sampdoria',
  'pisa': 'Pisa',
  'cremonese': 'Cremonese',
  
  // ==================== EREDIVISIE ====================
  'ajax': 'Ajax',
  'psv': 'PSV Eindhoven',
  'psv eindhoven': 'PSV Eindhoven',
  'eindhoven': 'PSV Eindhoven',
  'feyenoord': 'Feyenoord',
  'az': 'AZ Alkmaar',
  'az alkmaar': 'AZ Alkmaar',
  'alkmaar': 'AZ Alkmaar',
  'twente': 'FC Twente',
  'fc twente': 'FC Twente',
  'utrecht': 'FC Utrecht',
  'fc utrecht': 'FC Utrecht',
  'go ahead eagles': 'Go Ahead Eagles',
  'eagles': 'Go Ahead Eagles',
  'heerenveen': 'Heerenveen',
  'groningen': 'Groningen',
  'vitesse': 'Vitesse',
  'nec': 'NEC Nijmegen',
  'nijmegen': 'NEC Nijmegen',
  'sparta': 'Sparta Rotterdam',
  'sparta rotterdam': 'Sparta Rotterdam',
  'fortuna sittard': 'Fortuna Sittard',
  'volendam': 'Volendam',
  'excelsior': 'Excelsior',
  'zwolle': 'PEC Zwolle',
  'pec zwolle': 'PEC Zwolle',
  
  // ==================== PRIMEIRA LIGA (Portugal) ====================
  'benfica': 'Benfica',
  'porto': 'Porto',
  'fc porto': 'Porto',
  'sporting': 'Sporting CP',
  'sporting cp': 'Sporting CP',
  'sporting lisbon': 'Sporting CP',
  'sporting lisbonne': 'Sporting CP',
  'braga': 'Braga',
  'sc braga': 'Braga',
  'vitoria guimaraes': 'Guimaraes',
  'guimaraes': 'Guimaraes',
  'gil vicente': 'Gil Vicente',
  'rio ave': 'Rio Ave',
  'famalicao': 'Famalicao',
  'boavista': 'Boavista',
  'moreirense': 'Moreirense',
  'arouca': 'Arouca',
  'estoril': 'Estoril',
  'casa pia': 'Casa Pia',
  'vizela': 'Vizela',
  'chaves': 'Chaves',
  'portimonense': 'Portimonense',
  
  // ==================== CLUBS EUROPA LEAGUE ====================
  'rangers': 'Rangers',
  'celtic': 'Celtic',
  'galatasaray': 'Galatasaray',
  'fenerbahce': 'Fenerbahce',
  'besiktas': 'Besiktas',
  'olympiakos': 'Olympiakos',
  'paok': 'PAOK',
  'aek athens': 'AEK Athens',
  'aek': 'AEK Athens',
  'ajax': 'Ajax',
  'shakhtar': 'Shakhtar Donetsk',
  'shakhtar donetsk': 'Shakhtar Donetsk',
  'dynamo kyiv': 'Dynamo Kyiv',
  'kyiv': 'Dynamo Kyiv',
  'slavia prague': 'Slavia Praha',
  'slavia praha': 'Slavia Praha',
  'sparta prague': 'Sparta Praha',
  'sparta praha': 'Sparta Praha',
  'red star': 'Red Star Belgrade',
  'red star belgrade': 'Red Star Belgrade',
  'etoile rouge': 'Red Star Belgrade',
  'anderlecht': 'Anderlecht',
  'club brugge': 'Club Brugge',
  'bruges': 'Club Brugge',
  'union sg': 'Union Saint-Gilloise',
  'union saint gilloise': 'Union Saint-Gilloise',
  'basel': 'Basel',
  'young boys': 'Young Boys',
  'servette': 'Servette',
  'qarabag': 'Qarabag',
  'maccabi haifa': 'Maccabi Haifa',
  'maccabi tel aviv': 'Maccabi Tel Aviv',
  'sheriff': 'Sheriff Tiraspol',
  'sheriff tiraspol': 'Sheriff Tiraspol',
  'ferencvaros': 'Ferencvaros',
  'ludogorets': 'Ludogorets',
  'slovan bratislava': 'Slovan Bratislava',
  'bratislava': 'Slovan Bratislava',
  'dinamo zagreb': 'Dinamo Zagreb',
  'zagreb': 'Dinamo Zagreb'
};

export function normalizeTeamName(name) {
  if (!name) return name;
  
  const normalized = name.trim().toLowerCase();
  
  // Chercher dans le dictionnaire
  if (TEAM_NAMES[normalized]) {
    return TEAM_NAMES[normalized];
  }
  
  // Sinon retourner le nom original (capitalize)
  return name.trim()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

export default normalizeTeamName;
